name: Test Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    name: Workflow dorny Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        artifact: sanity-results          # artifact name
        name: Sanity Report Tests         # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results
